/**
 * Printable tasting-sheet builder. Pure: takes a flight + cellar temperature,
 * returns a self-contained HTML document (light theme, A4) with a preparation
 * plan (chill / decant lead times) and the serving order.
 *
 * Chilling rates from a cellar-temperature bottle (75 cl):
 *   - refrigerator (~4 °C): ≈ 10 min per °C to drop
 *   - ice + water bucket:   ≈ 2.5 min per °C to drop
 * e.g. 19 °C → 7 °C (sparkling): ~2 h fridge, ~30 min ice bucket.
 *
 * Alternative start ("fridge overnight"): bottles were refrigerated the night
 * before and sit at ~6 °C. The plan inverts — sparkling/whites stay in the
 * fridge until serving, reds are taken out early to warm up at room
 * temperature (≈ 8 min per °C to gain, e.g. 6 °C → 17 °C ≈ 1 h 30).
 */

import { isGuestWineKey, type TastingFlight, type FlightStop, type DirectiveNote } from "@/lib/tasting/engine";

type Translator = (key: string, values?: Record<string, string | number>) => string;

export interface ChillPlan {
  /** °C to drop from cellar temp to the middle of the serving range (0 = ready). */
  deltaC: number;
  fridgeMinutes: number;
  iceBathMinutes: number;
}

function roundTo5(min: number): number {
  return Math.max(5, Math.round(min / 5) * 5);
}

export function chillPlan(serveTempC: [number, number], cellarTempC: number): ChillPlan {
  const target = (serveTempC[0] + serveTempC[1]) / 2;
  const delta = cellarTempC - target;
  if (delta <= 1) return { deltaC: 0, fridgeMinutes: 0, iceBathMinutes: 0 };
  return {
    deltaC: delta,
    fridgeMinutes: roundTo5(delta * 10),
    iceBathMinutes: roundTo5(delta * 2.5),
  };
}

export type BottleStart = "cellar" | "ambient" | "fridgeOvernight";

export const FRIDGE_TEMP_C = 6;
const WARM_MIN_PER_C = 8; // bottle warming at room temperature

/** Minutes to warm a fridge-cold bottle up to the serving range (0 = keep chilled). */
export function warmMinutes(serveTempC: [number, number], startTempC: number): number {
  const target = (serveTempC[0] + serveTempC[1]) / 2;
  const delta = target - startTempC;
  if (delta <= 1) return 0;
  return roundTo5(delta * WARM_MIN_PER_C);
}

function esc(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function stopDisplayName(stop: FlightStop): string {
  const vintage = stop.vintage !== null ? ` ${stop.vintage}` : "";
  return `${stop.producerName} — ${stop.cuveeName}${vintage}`;
}

function formatPrice(eur: number | null | undefined, locale: string): string | null {
  // `eur` can be undefined at runtime (e.g. a flight generated by an older
  // client still in React state) — never let NaN reach the sheet.
  if (eur == null || !Number.isFinite(eur) || eur <= 0) return null;
  const formatted = new Intl.NumberFormat(locale, {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(eur);
  return `≈ ${formatted}`;
}

interface PrepAction {
  minutesBefore: number;
  label: string;
  wine: string;
  /** Cellar location(s) holding the bottle, e.g. "Casier A3 ×2, Casier B1". */
  location: string;
}

function locationSummary(stop: FlightStop): string {
  return stop.locations
    .map((l) => (stop.locations.length > 1 ? `${l.name} ×${l.qty}` : l.name))
    .join(", ");
}

export interface WineNote {
  description: string;
  funFact: string;
}

export interface PrintSheetInput {
  flight: TastingFlight;
  cellarTempC: number;
  locale: string;
  /** Translator scoped to the "tasting" namespace. */
  t: Translator;
  renderNote: (note: DirectiveNote) => string;
  /** AI-written blurb per wineKey (description + anecdote). Optional. */
  wineNotes?: Record<string, WineNote>;
  /** Where the bottles start: in the cellar (default) or fridge-cold since the night before. */
  bottlesStart?: BottleStart;
}

export function buildPrintHtml({
  flight,
  cellarTempC,
  locale,
  t,
  renderNote,
  wineNotes,
  bottlesStart = "cellar",
}: PrintSheetInput): string {
  // Both "cellar" and "ambient" are warm starts (chill down); only the fridge
  // start inverts the plan (warm the reds up). Ambient differs from cellar only
  // in wording and its default temperature (a room, not a temperature-controlled cave).
  const fromFridge = bottlesStart === "fridgeOvernight";
  const isAmbient = bottlesStart === "ambient";
  const modeName = t(`modes.${flight.mode}.name`);
  const axis = flight.selectedAxis ? ` · ${flight.selectedAxis.label}` : "";
  const date = new Date().toLocaleDateString(locale, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // ---- Preparation plan: one action per chill / decant, longest lead first ----
  const actions: PrepAction[] = [];
  for (const stop of flight.stops) {
    const wine = `${stop.position}. ${stopDisplayName(stop)}`;
    const location = locationSummary(stop);
    if (fromFridge) {
      // Bottles start fridge-cold: take the warmer-served ones out early.
      const warm = warmMinutes(stop.serveTempC, FRIDGE_TEMP_C);
      if (warm > 0) {
        actions.push({
          // The bottle must be out of the fridge to be decanted, so the
          // take-out happens at least as early as the decant.
          minutesBefore: Math.max(warm, stop.decantMinutes),
          label: t("print.actionTakeOut", {
            temp: FRIDGE_TEMP_C,
            low: stop.serveTempC[0],
            high: stop.serveTempC[1],
          }),
          wine,
          location,
        });
      }
    } else {
      const chill = chillPlan(stop.serveTempC, cellarTempC);
      if (chill.fridgeMinutes > 0) {
        actions.push({
          // Chilling happens on the closed bottle, so it must finish before the
          // wine is opened / decanted — shift its start back by the decant time.
          minutesBefore: chill.fridgeMinutes + stop.decantMinutes,
          label:
            t("print.actionFridge", {
              temp: cellarTempC,
              low: stop.serveTempC[0],
              high: stop.serveTempC[1],
            }) +
            " " +
            t("print.actionIceAlt", { minutes: chill.iceBathMinutes }),
          wine,
          location,
        });
      }
    }
    if (stop.decantMinutes > 0) {
      actions.push({
        minutesBefore: stop.decantMinutes,
        label: t("print.actionDecant"),
        wine,
        location,
      });
    }
  }
  actions.sort((a, b) => b.minutesBefore - a.minutesBefore);

  const prepRows =
    actions.length > 0
      ? actions
          .map(
            (a) => `<tr>
              <td class="time">${esc(t("print.hMinus", { minutes: a.minutesBefore }))}</td>
              <td><strong>${esc(a.wine)}</strong>${
                a.location ? ` <span class="loc">— ${esc(t("print.location", { location: a.location }))}</span>` : ""
              }<br/><span class="muted">${esc(a.label)}</span></td>
            </tr>`,
          )
          .join("")
      : `<tr><td colspan="2" class="muted">${esc(t(fromFridge ? "print.keepInFridge" : "print.nothingToPrep"))}</td></tr>`;

  // ---- Serving order ----
  const stopBlocks = flight.stops
    .map((stop) => {
      const facts: string[] = [
        t("print.serveAt", { low: stop.serveTempC[0], high: stop.serveTempC[1] }),
        t(`glass.${stop.glassType}`),
      ];
      if (fromFridge) {
        const warm = warmMinutes(stop.serveTempC, FRIDGE_TEMP_C);
        if (warm > 0) {
          facts.push(t("print.warmUpFact", { minutes: Math.max(warm, stop.decantMinutes) }));
        } else {
          facts.push(t("print.keepInFridge"));
        }
      } else {
        const chill = chillPlan(stop.serveTempC, cellarTempC);
        if (chill.fridgeMinutes > 0) {
          facts.push(t("print.chillFridge", { minutes: chill.fridgeMinutes }));
          facts.push(t("print.chillIce", { minutes: chill.iceBathMinutes }));
        } else {
          facts.push(t(isAmbient ? "print.readyAmbient" : "print.readyFromCellar"));
        }
      }
      if (stop.decantMinutes > 0) {
        facts.push(t("print.decant", { minutes: stop.decantMinutes }));
      }
      const meta = [
        stop.appellationName,
        stop.region,
        stop.grapes.join(", "),
        formatPrice(stop.avgPriceEur, locale),
        isGuestWineKey(stop.wineKey) ? t("print.guestTag") : null,
      ]
        .filter(Boolean)
        .join(" · ");
      const notes = stop.notes.map((n) => `<li>${esc(renderNote(n))}</li>`).join("");
      const blurb = wineNotes?.[stop.wineKey];
      return `<div class="stop">
        <div class="stop-head">
          <span class="pos">${stop.position}</span>
          <div>
            <p class="name">${esc(stopDisplayName(stop))}</p>
            <p class="meta">${esc(meta)}</p>
          </div>
        </div>
        ${blurb ? `<p class="desc">${esc(blurb.description)}</p>
        <p class="fact"><span class="fact-label">${esc(t("print.funFact"))}</span> ${esc(blurb.funFact)}</p>` : ""}
        <p class="facts">${facts.map(esc).join(" &nbsp;·&nbsp; ")}</p>
        ${notes ? `<ul class="notes">${notes}</ul>` : ""}
      </div>`;
    })
    .join("");

  const directives = flight.overall.map((n) => `<li>${esc(renderNote(n))}</li>`).join("");

  return `<!doctype html>
<html lang="${esc(locale)}">
<head>
<meta charset="utf-8"/>
<title>${esc(t("print.sheetTitle"))} — ${esc(modeName)}</title>
<style>
  @page { margin: 14mm; }
  * { box-sizing: border-box; }
  body { font: 10.5pt/1.5 Georgia, "Times New Roman", serif; color: #1c1a1e; margin: 0 auto; max-width: 180mm; padding: 8mm; }
  header { border-bottom: 2px solid #a53860; padding-bottom: 4mm; margin-bottom: 5mm; }
  h1 { font-size: 15pt; margin: 0; letter-spacing: 0.03em; }
  h1 small { color: #a53860; font-weight: normal; }
  .subline { margin: 1mm 0 0; color: #555; font-size: 9.5pt; }
  h2 { font-size: 11.5pt; color: #a53860; margin: 6mm 0 2mm; text-transform: uppercase; letter-spacing: 0.06em; }
  .hint { margin: 0 0 2mm; color: #777; font-size: 8.5pt; font-style: italic; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 1.6mm 2mm; border-bottom: 1px solid #ddd; vertical-align: top; }
  td.time { white-space: nowrap; font-weight: bold; width: 26mm; font-variant-numeric: tabular-nums; }
  .muted { color: #666; font-size: 9pt; }
  .loc { color: #a53860; font-size: 9pt; white-space: nowrap; }
  ul { margin: 0; padding-left: 5mm; }
  li { margin-bottom: 1mm; }
  .stop { border: 1px solid #ccc; border-radius: 2mm; padding: 3mm 4mm; margin-bottom: 3mm; page-break-inside: avoid; }
  .stop-head { display: flex; gap: 3mm; align-items: baseline; }
  .pos { font-size: 14pt; font-weight: bold; color: #a53860; min-width: 6mm; }
  .name { font-weight: bold; margin: 0; }
  .meta { margin: 0.5mm 0 0; color: #666; font-size: 9pt; }
  .facts { margin: 1.5mm 0 1mm; font-size: 9pt; color: #333; border-top: 1px dotted #ccc; padding-top: 1.5mm; }
  .desc { margin: 2mm 0 0; font-size: 9.5pt; }
  .fact { margin: 1.5mm 0 2mm; padding: 1.5mm 2.5mm; font-size: 9pt; background: #faf5ec; border-left: 2px solid #e5b25d; }
  .fact-label { font-weight: bold; color: #a53860; margin-right: 1mm; }
  .notes { font-size: 8.5pt; color: #555; }
  footer { margin-top: 6mm; color: #999; font-size: 8pt; text-align: center; }
</style>
</head>
<body>
<header>
  <h1>Achilles's Wines <small>· ${esc(t("print.sheetTitle"))}</small></h1>
  <p class="subline">${esc(modeName)}${esc(axis)} — ${esc(t("print.printedOn", { date }))} · ${esc(
    fromFridge
      ? t("print.fridgeAt", { temp: FRIDGE_TEMP_C })
      : t(isAmbient ? "print.ambientAt" : "print.cellarAt", { temp: cellarTempC }),
  )}</p>
</header>

<h2>${esc(t("print.prepTitle"))}</h2>
<p class="hint">${esc(t("print.prepSubtitle"))}</p>
<table>${prepRows}</table>

<h2>${esc(t("ui.directives"))}</h2>
<ul>${directives}</ul>

<h2>${esc(t("print.serviceTitle"))}</h2>
${stopBlocks}

<footer>Achilles's Wines${wineNotes && Object.keys(wineNotes).length > 0 ? ` — ${esc(t("print.aiDisclaimer"))}` : ""}</footer>
<script>addEventListener("load", () => setTimeout(() => print(), 200));</script>
</body>
</html>`;
}
